services:
  vue:
    build:
      context: ./vue
      dockerfile: Dockerfile
    container_name: devstack-vue
    command: "yarn dev"
    # command: sleep infinity
    # env_file:
    #   - ./vue/.env
    volumes:
      - ./vue:/vue
      - /vue/node_modules
      - /vue/build
    ports:
      - 5173:5173
    networks:
      - cosmobots-net
    environment:
      VITE_FLOW_MANAGER_URL: http://localhost:9001

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: cosmobots-api
    # command: "sleep infinity"
    command: "bin/rails server -b 0.0.0.0"
    environment:
      RAILS_ENV: development
      # RAILS_MASTER_KEY: 29fdc366d32524c3bebd76d4c962acec
    volumes:
      - ./api:/rails
    ports:
      - 3000:3000
    networks:
      - cosmobots-net

networks:
  cosmobots-net:
